### ISSUE TITLE
Wrong localization orientation in Autoware

### ISSUE THREAD

**Issue by lchojnack** [autowarefoundation/AWSIM-Labs#79] opened 2024-05-23 10:28 UTC
The current AWSIM `main` branch causes wrong localization orientation in Autoware.
I think the issue could be caused by recent orientation changes in the `sensor_kit_base_link` child components.
More investigation is needed

![Screenshot_20240523_122322](https://github.com/autowarefoundation/AWSIM/assets/8416175/57baa64d-fcb8-47c6-b0ed-9aa077cbb215)

**Comment by mozhoku** [comment] 2024-05-23 11:23
@lchojnack did you get this bug with default scene?

~~Could you try again after using the dynamic sensor placement tool.~~

Okay I got the same error. Looking into it.


This morning, when rebasing https://github.com/autowarefoundation/AWSIM/pull/71, I've noticed that the all transform values on the default vehicle prefab is 0, that might be the cause.

**Comment by lchojnack** [comment] 2024-05-23 12:26
@mozhoku Yes, I've get it on default scene without any changes.

**Comment by mozhoku** [comment] 2024-05-23 12:35
~~Okay found the reason.
When importing the sensor configuration with the dynamic sensor importing tool, the **"velodyne_top_base_link"** transform gets **~(-90°)** rotation on **Y axis**. After defaulting it to **0°** it localizes properly.~~

Sorry for the trouble. I'll fix it in a separate PR since I'm the one who merged it.

**Comment by mozhoku** [comment] 2024-05-24 11:20
~~Opened a PR for this issue in autoware_individual_params repo:~~
~~- https://github.com/autowarefoundation/autoware_individual_params/pull/51~~


After looking into this with @xmfcx he noticed that top lidars Frame ID is "sensor_kit_base_link". We will change this ID to "velodyne_top_base_link".

**Closed as completed** 2024-05-24 12:53 UTC
Labels: type:bug
